### PR TITLE
Leftover compilation errors after bfd42a342dcf693cfae8a0eb8ec2056e6f13e310

### PR DESCRIPTION
**Pull request by sashakh**
## Issue

src/routing/libosrm_wrapper.cpp was not updated.

## Tasks

 - [x] so fixing )
 - [x] also small makefile improvement
 - [ ] review

### CODE REVIEW

**Comment by sashakh** [comment]
In addition we could add something like this in 'makefile':
```
dep:
        $(CXX) -MM $(CXXFLAGS) $(SRC) main.cpp \
                | sed -e 's/^.*\.o: \(.*\)\.cpp/\1.o: \1.cpp/' \
                > .depend
-include .depend
```
, and then to run 'make dep' (only once). So 'make' will track all changed header files and rebuild affected sources automatically.

**Comment by jcoupey** [comment]
@sashakh thanks for updating the missing bits. Using `$(RM)` is nicer too.

About the `dep` part, I think I don't really get the difference. Do you see this as a replacement for the current:

```makefile
SRC = $(wildcard *.cpp)\
	$(wildcard ./algorithms/*.cpp)\
	$(wildcard ./routing/*.cpp)\
	$(wildcard ./problems/*.cpp)\
	$(wildcard ./problems/*/*.cpp)\
	$(wildcard ./problems/*/heuristics/*.cpp)\
	$(wildcard ./structures/abstract/*.cpp)\
	$(wildcard ./structures/vroom/*.cpp)\
	$(wildcard ./structures/vroom/input/*.cpp)\
	$(wildcard ./structures/vroom/solution/*.cpp)\
	$(wildcard ./structures/*.cpp)\
	$(wildcard ./utils/*.cpp)
```

**Comment by sashakh** [comment]
No, of course not. SRC should stay as it is. I'm about build dependencies where source file includes potentially changed header files.

**Comment by jcoupey** [comment]
I get it now (I'm really no makefile expert...)

Looks like a good way to make sure all dependencies are handled. But what I don't get is why having `$(MAIN)` depend on `$(OBJ)` is not enough (provided that the `$(SRC)` list is exhaustive). Are we just missing the cases where there is a `.h` file without corresponding `.cpp`?

**Comment by sashakh** [comment]
Yes, exactly. In makefile now you have:
```
$(MAIN) : $(OBJ) main.o
...
%.o : %.cpp %.h
```
So when some .h file is changed the rules above force 'make' to rebuild its correspondent .cpp file and then $(MAIN). But if changed .h is also included (directly or indirectly) in some another .cpp (or .h) file, those dependant files will not rebuilt. This actually was a reason for the last build failure.
Adding special 'dep' rules solves this issue. In proposed method 'make dep' should be executed only once (also when new .h files are added, included) and then all dependencies are kept in generated .depend makefile.
If you wish I can add this patch to PR.

**Comment by jcoupey** [comment]
The reason I skipped the `libosrm_wrapper.cpp` refactoring was that it was left out of compilation altogether during my checks, as `libosrm` wasn't installed.

I'll merge the PR as it is, thanks for the fix and the additional suggestion! For the dependency handling, I'd like to try to have any change result in a `.o` update so the current targets should be enough. It should just be a matter of making sure there is no single header file without matching `.cpp`.

**Comment by sashakh** [comment]
Ah ok, I see, in your case it was a missed anyway (with or without ```make dep```).

Regarding to dependencies. For me it worked up to I did ```make dep```.
I think, that the current targets are not enough, just small example:
Let's change ```./structures/vroom/location.h```:
```
$ touch ./structures/vroom/location.h
$ make
g++ -std=c++14 -Wextra -Wpedantic -Wall -O3 -DBOOST_LOG_DYN_LINK -std=c++14 -DBOOST_TEST_DYN_LINK -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_FILESYSTEM_NO_DEPRECATED -I/usr/include/lua5.2 -I/usr/local/include -I/usr/local/include/osrm -D LIBOSRM=true -c structures/vroom/location.cpp -o structures/vroom/location.o
mkdir -p ../bin
g++ -std=c++14 -Wextra -Wpedantic -Wall -O3 -DBOOST_LOG_DYN_LINK -std=c++14 -DBOOST_TEST_DYN_LINK -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_FILESYSTEM_NO_DEPRECATED -I/usr/include/lua5.2 -I/usr/local/include -I/usr/local/include/osrm -D LIBOSRM=true -o ../bin/vroom main.o algorithms/munkres.o algorithms/kruskal.o routing/routed_wrapper.o routing/libosrm_wrapper.o problems/vrp.o problems/tsp/tsp.o problems/tsp/heuristics/christofides.o problems/tsp/heuristics/local_search.o structures/abstract/matrix.o structures/abstract/edge.o structures/abstract/undirected_graph.o structures/vroom/location.o structures/vroom/input/input.o structures/vroom/solution/summary.o structures/vroom/solution/route.o structures/vroom/solution/step.o structures/vroom/solution/computing_times.o structures/vroom/solution/solution.o utils/output_json.o utils/input_parser.o utils/exceptions.o utils/version.o -lboost_system -lboost_log -lboost_log_setup -lpthread -lboost_thread -L/usr/local/lib -losrm -fuse-ld=gold -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-O1 -Wl,--hash-style=gnu -Wl,--sort-common -lboost_filesystem -lboost_iostreams -lrt -ltbb
mkdir -p ../lib
ar cr ../lib/libvroom.a main.o algorithms/munkres.o algorithms/kruskal.o routing/routed_wrapper.o routing/libosrm_wrapper.o problems/vrp.o problems/tsp/tsp.o problems/tsp/heuristics/christofides.o problems/tsp/heuristics/local_search.o structures/abstract/matrix.o structures/abstract/edge.o structures/abstract/undirected_graph.o structures/vroom/location.o structures/vroom/input/input.o structures/vroom/solution/summary.o structures/vroom/solution/route.o structures/vroom/solution/step.o structures/vroom/solution/computing_times.o structures/vroom/solution/solution.o utils/output_json.o utils/input_parser.o utils/exceptions.o utils/version.o
```
,  with current makefile this will only rebuild ```structures/vroom/location.cpp``` file and relink vroom. It will not try to rebuild other ```.cpp``` files affected by ```location.h```.
Now with dependencies generated:
```
$ make dep
$ touch ./structures/vroom/location.h
$ make 
g++ -std=c++14 -Wextra -Wpedantic -Wall -O3 -DBOOST_LOG_DYN_LINK -std=c++14 -DBOOST_TEST_DYN_LINK -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_FILESYSTEM_NO_DEPRECATED -I/usr/include/lua5.2 -I/usr/local/include -I/usr/local/include/osrm -D LIBOSRM=true -c main.cpp -o main.o
g++ -std=c++14 -Wextra -Wpedantic -Wall -O3 -DBOOST_LOG_DYN_LINK -std=c++14 -DBOOST_TEST_DYN_LINK -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_FILESYSTEM_NO_DEPRECATED -I/usr/include/lua5.2 -I/usr/local/include -I/usr/local/include/osrm -D LIBOSRM=true -c routing/routed_wrapper.cpp -o routing/routed_wrapper.o
g++ -std=c++14 -Wextra -Wpedantic -Wall -O3 -DBOOST_LOG_DYN_LINK -std=c++14 -DBOOST_TEST_DYN_LINK -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_FILESYSTEM_NO_DEPRECATED -I/usr/include/lua5.2 -I/usr/local/include -I/usr/local/include/osrm -D LIBOSRM=true -c routing/libosrm_wrapper.cpp -o routing/libosrm_wrapper.o
g++ -std=c++14 -Wextra -Wpedantic -Wall -O3 -DBOOST_LOG_DYN_LINK -std=c++14 -DBOOST_TEST_DYN_LINK -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_FILESYSTEM_NO_DEPRECATED -I/usr/include/lua5.2 -I/usr/local/include -I/usr/local/include/osrm -D LIBOSRM=true -c problems/vrp.cpp -o problems/vrp.o
g++ -std=c++14 -Wextra -Wpedantic -Wall -O3 -DBOOST_LOG_DYN_LINK -std=c++14 -DBOOST_TEST_DYN_LINK -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_FILESYSTEM_NO_DEPRECATED -I/usr/include/lua5.2 -I/usr/local/include -I/usr/local/include/osrm -D LIBOSRM=true -c problems/tsp/tsp.cpp -o problems/tsp/tsp.o
g++ -std=c++14 -Wextra -Wpedantic -Wall -O3 -DBOOST_LOG_DYN_LINK -std=c++14 -DBOOST_TEST_DYN_LINK -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_FILESYSTEM_NO_DEPRECATED -I/usr/include/lua5.2 -I/usr/local/include -I/usr/local/include/osrm -D LIBOSRM=true -c structures/vroom/location.cpp -o structures/vroom/location.o
g++ -std=c++14 -Wextra -Wpedantic -Wall -O3 -DBOOST_LOG_DYN_LINK -std=c++14 -DBOOST_TEST_DYN_LINK -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_FILESYSTEM_NO_DEPRECATED -I/usr/include/lua5.2 -I/usr/local/include -I/usr/local/include/osrm -D LIBOSRM=true -c structures/vroom/input/input.cpp -o structures/vroom/input/input.o
g++ -std=c++14 -Wextra -Wpedantic -Wall -O3 -DBOOST_LOG_DYN_LINK -std=c++14 -DBOOST_TEST_DYN_LINK -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_FILESYSTEM_NO_DEPRECATED -I/usr/include/lua5.2 -I/usr/local/include -I/usr/local/include/osrm -D LIBOSRM=true -c structures/vroom/solution/route.cpp -o structures/vroom/solution/route.o
g++ -std=c++14 -Wextra -Wpedantic -Wall -O3 -DBOOST_LOG_DYN_LINK -std=c++14 -DBOOST_TEST_DYN_LINK -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_FILESYSTEM_NO_DEPRECATED -I/usr/include/lua5.2 -I/usr/local/include -I/usr/local/include/osrm -D LIBOSRM=true -c structures/vroom/solution/step.cpp -o structures/vroom/solution/step.o
g++ -std=c++14 -Wextra -Wpedantic -Wall -O3 -DBOOST_LOG_DYN_LINK -std=c++14 -DBOOST_TEST_DYN_LINK -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_FILESYSTEM_NO_DEPRECATED -I/usr/include/lua5.2 -I/usr/local/include -I/usr/local/include/osrm -D LIBOSRM=true -c structures/vroom/solution/solution.cpp -o structures/vroom/solution/solution.o
g++ -std=c++14 -Wextra -Wpedantic -Wall -O3 -DBOOST_LOG_DYN_LINK -std=c++14 -DBOOST_TEST_DYN_LINK -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_FILESYSTEM_NO_DEPRECATED -I/usr/include/lua5.2 -I/usr/local/include -I/usr/local/include/osrm -D LIBOSRM=true -c utils/output_json.cpp -o utils/output_json.o
g++ -std=c++14 -Wextra -Wpedantic -Wall -O3 -DBOOST_LOG_DYN_LINK -std=c++14 -DBOOST_TEST_DYN_LINK -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_FILESYSTEM_NO_DEPRECATED -I/usr/include/lua5.2 -I/usr/local/include -I/usr/local/include/osrm -D LIBOSRM=true -c utils/input_parser.cpp -o utils/input_parser.o
mkdir -p ../bin
g++ -std=c++14 -Wextra -Wpedantic -Wall -O3 -DBOOST_LOG_DYN_LINK -std=c++14 -DBOOST_TEST_DYN_LINK -DBOOST_SPIRIT_USE_PHOENIX_V3 -DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_FILESYSTEM_NO_DEPRECATED -I/usr/include/lua5.2 -I/usr/local/include -I/usr/local/include/osrm -D LIBOSRM=true -o ../bin/vroom main.o algorithms/munkres.o algorithms/kruskal.o routing/routed_wrapper.o routing/libosrm_wrapper.o problems/vrp.o problems/tsp/tsp.o problems/tsp/heuristics/christofides.o problems/tsp/heuristics/local_search.o structures/abstract/matrix.o structures/abstract/edge.o structures/abstract/undirected_graph.o structures/vroom/location.o structures/vroom/input/input.o structures/vroom/solution/summary.o structures/vroom/solution/route.o structures/vroom/solution/step.o structures/vroom/solution/computing_times.o structures/vroom/solution/solution.o utils/output_json.o utils/input_parser.o utils/exceptions.o utils/version.o -lboost_system -lboost_log -lboost_log_setup -lpthread -lboost_thread -L/usr/local/lib -losrm -fuse-ld=gold -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-O1 -Wl,--hash-style=gnu -Wl,--sort-common -lboost_filesystem -lboost_iostreams -lrt -ltbb
mkdir -p ../lib
ar cr ../lib/libvroom.a main.o algorithms/munkres.o algorithms/kruskal.o routing/routed_wrapper.o routing/libosrm_wrapper.o problems/vrp.o problems/tsp/tsp.o problems/tsp/heuristics/christofides.o problems/tsp/heuristics/local_search.o structures/abstract/matrix.o structures/abstract/edge.o structures/abstract/undirected_graph.o structures/vroom/location.o structures/vroom/input/input.o structures/vroom/solution/summary.o structures/vroom/solution/route.o structures/vroom/solution/step.o structures/vroom/solution/computing_times.o structures/vroom/solution/solution.o utils/output_json.o utils/input_parser.o utils/exceptions.o utils/version.o
```
In that case ```make``` rebuild each ```.cpp``` file where ```location.h``` was directly or indirectly included.

Of course it is optional and there are more ways to handle dependendencies (for example generate individual ```.d``` files with -MD flags) or to not handle it at all and care about proper builds manually. )

**Pull request merged**
