### PR TITLE
implicit instantiation of undefined template error fixed for macos g++ compiler

### PR DESCRIPTION
**Pull request by iedmrc**
## Issue
#231 

Fixed

### CODE REVIEW

**Comment by jcoupey** [comment]
Thanks for the PR!

Including `string` in `src/structures/typedefs.h` does make sense to fix the build errors you're experiencing. But is that not enough? I don't get the need for another inclusion in `src/structures/generic/edge.h`, `src/structures/generic/matrix.h` and ` src/structures/vroom/raw_route.h`?

**Comment by iedmrc** [comment]
Ah yes. I got errors with this order:
src/structures/generic/edge.h
src/structures/generic/matrix.h
src/structures/vroom/raw_route.h
src/structures/typedefs.h

So I added `#include <string>` one by one to all in order to solve the problem 😄 
I can push again with only `src/structures/typedefs.h` included `#include <string>` if you say?

**Comment by jcoupey** [comment]
> I can push again with only src/structures/typedefs.h included #include <string>

If it's enough to solve your compilation problem, then yes please! Also it would be great if you could add a line to the Unreleased/fixed entry in the changelog with the issue number.

**Comment by vishalmhjn** [comment]
> Thanks for the PR!
> 
> Including `string` in `src/structures/typedefs.h` does make sense to fix the build errors you're experiencing. But is that not enough? I don't get the need for another inclusion in `src/structures/generic/edge.h`, `src/structures/generic/matrix.h` and ` src/structures/vroom/raw_route.h`?

This worked for me

**Pull request merged**
