### PR TITLE
Pickup and delivery

### PR DESCRIPTION
**Pull request by jcoupey**
## Issue

This PR is a work in progress toward #189 to solve problems including pickup-and-delivery scenarios (with precedence constraints, as opposed to #241 that is already implemented). For all pairs of pickup/delivery jobs, a solution is expected to be valid wrt two new constraints.

- *coupling*: pickup and delivery must be serviced by the same vehicle
- *precedence*: pickup must happen before delivery

## Tasks

 - [x] Define new objects to model pickup-and-delivery scenarios
 - [x] Adjust existing heuristics to include paired jobs and produce valid solutions wrt new constraints.
 - [x] Restrict current local search neighbours to the one that are valid wrt new constraints 
 - [x] Handle P&D pairs for (intra) CROSS and Mixed Exchange + Or-opt
 - [x] Add new dedicated operator to shift a P&D to another route
 - [x] ~~Add other operator(s) dedicated to P&D?~~
 - [x] Adjust `remove_from_routes` and `try_job_additions` logic to handle P&D pairs in local search
 - [x] Benchmark approach on academic and real-life instances
 - [x] Test on mixed problems containing single jobs and shipments
 - [x] Adjust output `step` type
 - [x] Consider P&D pairs in `Input::set_compatibility`
 - [x] Update `libvroom` example
 - [x] Update `docs/API.md`
 - [x] Update `CHANGELOG.md`
 - [x] review

### CODE REVIEW

**Comment by K-Leon** [comment]
This looks awesome! If you need help testing just ping me!

**Comment by jcoupey** [comment]
@K-Leon feedback is always highly appreciated! Please share your results if you can run some tests.

The work on this PR is not done yet but it's in a good state for testing because 1/ I don't expect [the `shipment` API](https://github.com/VROOM-Project/vroom/blob/feature/pickup-and-delivery/docs/API.md#shipments) to change now and 2/ the last 3 commits significantly improved overall results so the solution quality should already be OK.

**Comment by K-Leon** [comment]
Sounds awesome @jcoupey.

I didn't exactly understand from the API how to set up a shipment with pickup and its delivery on the same vehicle. (Dependent to each other)

May you give me a short hint? I'll then setup everything in my testing envrionment and try to generate some examples at changing locations and combinations.

**Comment by jcoupey** [comment]
> how to set up a shipment with pickup and its delivery on the same vehicle

This is the point of having a new `shipment` object in the API that embeds both "jobs". In term of modelling, defining a `shipment` implies you expect its `pickup` and `delivery` to be performed in the right order on the same route. And the carried amount only affects vehicle capacity between pickup and delivery.

There is no example currently in the API docs, so here is a sample extract from one of the benchmark files I'm using during development:
```
{
  "shipments": [
    {
      "amount": [
        10
      ],
      "pickup": {
        "id": 3,
        "time_windows": [
          [
            65000,
            146000
          ]
        ],
        "service": 90000,
        "location": [
          42.0,
          66.0
        ]
      },
      "delivery": {
        "id": 75,
        "time_windows": [
          [
            997000,
            1068000
          ]
        ],
        "service": 90000,
        "location": [
          45.0,
          65.0
        ]
      }
    }
  ]
}
```

Note that you should be able to mix regular jobs (single deliveries or pickups) with shipments (aka pickup-and-delivery jobs) in the same problem instance.

**Comment by K-Leon** [comment]
@jcoupey Sorry for the late response. I tested it and pushed a lot of test traffic over it. There seems to be no regressions with the previous features. At least nothing i noticed - also the conditions seem to work great! I looks like you did an awesome job.

**Comment by jcoupey** [comment]
@K-Leon thanks for testing and reporting, that's really helpful.

The biggest part of what needed to be adjusted to handle P&D is done now but there is still some work before merging and tagging a new release. The changes to be expected are small, but hopefully we'll still get slight gains on solution costs.

**Comment by jcoupey** [comment]
@K-Leon out of curiosity, where your tests about shipments-only situations or did you also try solving instances mixing shipments and regular jobs? Asking because I've not done much tests so far on the latter. Also some of the last day commits target this use-case through specific local search operators that involve moving around a job and a shipment at once.

**Comment by Reggerriee** [comment]
> ## Issue
> This PR is a work in progress toward #189 to solve problems including pickup-and-delivery scenarios (with precedence constraints, as opposed to #241 that is already implemented). For all pairs of pickup/delivery jobs, a solution is expected to be valid wrt two new constraints.
> 
> * _coupling_: pickup and delivery must be serviced by the same vehicle
> * _precedence_: pickup must happen before delivery
> 
> ## Tasks
> * [x]  Define new objects to model pickup-and-delivery scenarios
> * [x]  Adjust existing heuristics to include paired jobs and produce valid solutions wrt new constraints.
> * [x]  Restrict current local search neighbours to the one that are valid wrt new constraints
> * [x]  Handle P&D pairs for (intra) CROSS and Mixed Exchange + Or-opt
> * [x]  Add new dedicated operator to shift a P&D to another route
> * [x]  ~Add other operator(s) dedicated to P&D?~
> * [x]  Adjust `remove_from_routes` and `try_job_additions` logic to handle P&D pairs in local search
> * [x]  Benchmark approach on academic and real-life instances
> * [x]  Test on mixed problems containing single jobs and shipments
> * [x]  Adjust output `step` type
> * [x]  Consider P&D pairs in `Input::set_compatibility`
> * [x]  Update `libvroom` example
> * [x]  Update `docs/API.md`
> * [x]  Update `CHANGELOG.md`
> * [x]  review

Hi,
I would like to ask whether this has been achieved? "* _precedence_: pickup must happen before delivery"
Realizing this is a problem for me and I want to ask you for information.
Thanks for your help.

**Comment by jcoupey** [comment]
@Reggerriee as you can see, this PR has been merged. It's now part of the core features [as of v1.6.0](https://github.com/VROOM-Project/vroom/blob/master/CHANGELOG.md#v160---2020-02-18).

Use `shipment` objects to describe a pickup-and-delivery scenario.

**Comment by Reggerriee** [comment]
> @Reggerriee as you can see, this PR has been merged. It's now part of the core features [as of v1.6.0](https://github.com/VROOM-Project/vroom/blob/master/CHANGELOG.md#v160---2020-02-18).
> 
> Use `shipment` objects to describe a pickup-and-delivery scenario.

Unfortunately, I do not know how to use. Can you possibly send an example where two jobs are assigned and which pickup is specified for which delivery?

This is my example:
{"jobs":[{"id":1,"service":600,"delivery":[1],"description":"Érd, 2030 Magyarország","location":[18.9016904,47.3571428]},{"id":2,"service":600,"delivery":[1],"description":"Százhalombatta, 2440 Magyarország","location":[18.9065897,47.3107008]},{"id":3,"service":600,"pickup":[1],"description":"Törökbálint, Magyarország","location":[18.9108101,47.4384914]},{"id":4,"service":600,"delivery":[1],"description":"Diósd, Magyarország","location":[18.9434797,47.4082916]},{"id":5,"service":600,"pickup":[1],"description":"Budaörs, Magyarország","location":[18.9529586,47.4621396]},{"id":6,"service":600,"delivery":[1],"description":"Sóskút, Magyarország","location":[18.8277597,47.4046702]},{"id":7,"service":600,"delivery":[1],"description":"Pusztazámor, Magyarország","location":[18.7830465,47.4044249]},{"id":8,"service":600,"delivery":[1],"description":"Biatorbágy, Magyarország","location":[18.8205591,47.4706818]},{"id":9,"service":600,"delivery":[1],"description":"Etyek, Magyarország","location":[18.751179,47.4467098]},{"id":10,"service":600,"delivery":[1],"description":"Herceghalom, Magyarország","location":[18.743256,47.4979399]}],"options":{"g":true},"vehicles":[{"id":1,"capacity":[5],"start":[18.9016904,47.3571428],"startDescription":"Érd, 2030 Magyarország","end":[18.9016904,47.3571428],"endDescription":"Érd, 2030 Magyarország"},{"id":2,"capacity":[5],"start":[18.9016904,47.3571428],"startDescription":"Érd, 2030 Magyarország","end":[18.9016904,47.3571428],"endDescription":"Érd, 2030 Magyarország"}]}

Where should I indicate which delivery the pickup belongs to?

Thanks for your answer.

**Comment by braktar** [comment]
Pickup-and-delivery pairs are defined not as jobs, but as shipments.

Here is the sample which displays how to build the json :
https://github.com/VROOM-Project/vroom/blob/24a6dd54175f40f2fb58be1c2ff76dd951a957f8/docs/example_1.json#L124

you have to specifically define one pickup 'activity' and one delivery 'activity'.
Jobs which are not linked can still be defined as jobs in parallel

**Comment by Reggerriee** [comment]
> Pickup-and-delivery pairs are defined not as jobs, but as shipments.
> 
> Here is the sample which displays how to build the json :
> https://github.com/VROOM-Project/vroom/blob/24a6dd54175f40f2fb58be1c2ff76dd951a957f8/docs/example_1.json#L124
> 
> you have to specifically define one pickup 'activity' and one delivery 'activity'.
> Activities which are not linked can still be defined as jobs in parallel

Thank you for your answer 👍

**Pull request merged**
